#!/bin/bash

project_hooks=$(git config get --local core.hooksPath)
if [ -n "$project_hooks" ] && [ -d "$project_hooks" ]; then
  if [ -x "$project_hooks/prepare-commit-msg" ]; then
    /home/ai/Projects/env/bin/dev CI=1 $project_hooks/prepare-commit-msg
  fi
fi
